name: Terraform resource creation using CI

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v4

      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: <v1.7.5>

      
      - name: Configure AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> $GITHUB_ENV
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: Terraform-VPC

      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: Terraform-VPC

      - name: Terraform Plan
        id: plan
        run: terraform plan
        working-directory: Terraform-VPC

      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve
        working-directory: Terraform-VPC

      - name: Terraform Destroy
        id: destroy
        run: terraform destroy --auto-approve
        working-directory: Terraform-VPC

      - name: Cleanup
        run: rm -rf .terraform
